// Auto-generated fields for SharePoint list: Requests
// Generated on: 2025-10-31 22:59:07

export const RequestsFields = {
  ContentType: 'ContentType',
  ID: 'ID',
  RequestId: 'Title',
  Status: 'Status',
  Purpose: 'Purpose',
  Attorney: 'Attorney',
  Department: 'Department',
  OnHoldBy: 'OnHoldBy',
  CloseoutBy: 'CloseoutBy',
  CloseoutOn: 'CloseoutOn',
  TrackingId: 'TrackingId',
  CancelledBy: 'CancelledBy',
  CancelledOn: 'CancelledOn',
  RequestType: 'RequestType',
  SubmittedBy: 'SubmittedBy',
  SubmittedOn: 'SubmittedOn',
  CancelReason: 'CancelReason',
  IsRetailUse: 'IsRetailUse',
  OnHoldSince: 'OnHoldSince',
  RequestTitle: 'RequestTitle',
  OnHoldReason: 'OnHoldReason',
  OtherApproval: 'OtherApproval',
  RushRationale: 'RushRationale',
  IsRushRequest: 'IsRushRequest',
  PreviousStatus: 'PreviousStatus',
  ReviewAudience: 'ReviewAudience',
  SubmissionItem: 'SubmissionItem',
  SubmissionType: 'SubmissionType',
  AdditionalParty: 'AdditionalParty',
  // FINRA Audience & Product Fields
  FINRAAudienceCategory: 'FINRAAudienceCategory',
  Audience: 'Audience',
  USFunds: 'USFunds',
  UCITS: 'UCITS',
  SeparateAcctStrategies: 'SeparateAcctStrategies',
  SeparateAcctStrategiesIncl: 'SeparateAcctStrategiesIncl',
  HasSMEApproval: 'HasSMEApproval',
  SMEApprovalNotes: 'SMEApprovalNotes',
  ResearchAnalyst: 'ResearchAnalyst',
  ResearchAnalystApprovalNotes: 'ResearchAnalystApprovalNotes',
  DateOfFirstUse: 'DateOfFirstUse',
  PortfolioManager: 'PortfolioManager',
  PortfolioMgrApprovalNotes: 'PortfolioMgrApprovalNotes',
  PriorSubmissions: 'PriorSubmissions',
  SMEApprovalDate: 'SMEApprovalDate',
  HasOtherApproval: 'HasOtherApproval',
  OtherApprovalNotes: 'OtherApprovalNotes',
  LegalReviewNotes: 'LegalReviewNotes',
  LegalReviewCompletedOn: 'LegalReviewCompletedOn',
  LegalReviewCompletedBy: 'LegalReviewCompletedBy',
  TargetReturnDate: 'TargetReturnDate',
  DistributionMethod: 'DistributionMethod',
  LegalReviewStatus: 'LegalReviewStatus',
  OtherApprovalDate: 'OtherApprovalDate',
  LegalReviewOutcome: 'LegalReviewOutcome',
  OtherApprovalTitle: 'OtherApprovalTitle',
  PerformanceApprover: 'PerformanceApprover',
  AttorneyAssignNotes: 'AttorneyAssignNotes',
  SubjectMatterExpert: 'SubjectMatterExpert',
  TotalTurnaroundDays: 'TotalTurnaroundDays',
  PriorSubmissionNotes: 'PriorSubmissionNotes',
  CommunicationsApprover: 'CommunicationsApprover',
  CommunicationsApprovalNotes: 'CommunicationsApprovalNotes',
  ComplianceReviewNotes: 'ComplianceReviewNotes',
  ComplianceReviewCompletedOn: 'ComplianceReviewCompletedOn',
  ComplianceReviewCompletedBy: 'ComplianceReviewCompletedBy',
  LegalStatusUpdatedBy: 'LegalStatusUpdatedBy',
  LegalStatusUpdatedOn: 'LegalStatusUpdatedOn',
  SubmittedForReviewBy: 'SubmittedForReviewBy',
  SubmittedForReviewOn: 'SubmittedForReviewOn',
  ComplianceReviewStatus: 'ComplianceReviewStatus',
  ExpectedTurnaroundDate: 'ExpectedTurnaroundDate',
  HasPerformanceApproval: 'HasPerformanceApproval',
  PerformanceApprovalNotes: 'PerformanceApprovalNotes',
  ComplianceReviewOutcome: 'ComplianceReviewOutcome',
  PerformanceApprovalDate: 'PerformanceApprovalDate',
  IsForesideReviewRequired: 'IsForesideReviewRequired',
  CommunicationsApprovalDate: 'CommunicationsApprovalDate',
  ComplianceStatusUpdatedBy: 'ComplianceStatusUpdatedBy',
  ComplianceStatusUpdatedOn: 'ComplianceStatusUpdatedOn',
  HasResearchAnalystApproval: 'HasResearchAnalystApproval',
  HasPortfolioManagerApproval: 'HasPortfolioManagerApproval',
  ResearchAnalystApprovalDate: 'ResearchAnalystApprovalDate',
  PortfolioManagerApprovalDate: 'PortfolioManagerApprovalDate',
  SubmittedToAssignAttorneyBy: 'SubmittedToAssignAttorneyBy',
  SubmittedToAssignAttorneyOn: 'SubmittedToAssignAttorneyOn',
  RequiresCommunicationsApproval: 'RequiresCommunicationsApproval',
  Created: 'Created',
  Author: 'Author',
  Modified: 'Modified',
  Editor: 'Editor',
  // Time Tracking - Legal Intake
  LegalIntakeLegalAdminHours: 'LegalIntakeLegalAdminHours',
  LegalIntakeSubmitterHours: 'LegalIntakeSubmitterHours',
  // Time Tracking - Legal Review
  LegalReviewAttorneyHours: 'LegalReviewAttorneyHours',
  LegalReviewSubmitterHours: 'LegalReviewSubmitterHours',
  // Time Tracking - Compliance Review
  ComplianceReviewReviewerHours: 'ComplianceReviewReviewerHours',
  ComplianceReviewSubmitterHours: 'ComplianceReviewSubmitterHours',
  // Time Tracking - Closeout
  CloseoutReviewerHours: 'CloseoutReviewerHours',
  CloseoutSubmitterHours: 'CloseoutSubmitterHours',
  // Time Tracking - Totals
  TotalReviewerHours: 'TotalReviewerHours',
  TotalSubmitterHours: 'TotalSubmitterHours',
  // Admin Override Audit Trail
  AdminOverrideNotes: 'AdminOverrideNotes',
  // Closeout
  CloseoutNotes: 'CloseoutNotes'
} as const;

